// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKQqWUpM0yRIb_CbiobZUG1kt44xslV3A',
    appId: '1:208068800642:web:a85cf602795ccb6028849b',
    messagingSenderId: '208068800642',
    projectId: 'nepal-top-f8814',
    authDomain: 'nepal-top-f8814.firebaseapp.com',
    storageBucket: 'nepal-top-f8814.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK5fHhmjQ8GQ-wSaJeSj-8eB6WaWDDYCM',
    appId: '1:208068800642:android:9ecd0134cd7591a528849b',
    messagingSenderId: '208068800642',
    projectId: 'nepal-top-f8814',
    storageBucket: 'nepal-top-f8814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVX84DoyJXBjNcMn48TYIWOvNPEL1YO4w',
    appId: '1:208068800642:ios:d9e29b9f266a905728849b',
    messagingSenderId: '208068800642',
    projectId: 'nepal-top-f8814',
    storageBucket: 'nepal-top-f8814.appspot.com',
    iosClientId: '208068800642-re1f7iilk89oe0d19qr02c0ioj4l7m3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.nepaltop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVX84DoyJXBjNcMn48TYIWOvNPEL1YO4w',
    appId: '1:208068800642:ios:d9e29b9f266a905728849b',
    messagingSenderId: '208068800642',
    projectId: 'nepal-top-f8814',
    storageBucket: 'nepal-top-f8814.appspot.com',
    iosClientId: '208068800642-re1f7iilk89oe0d19qr02c0ioj4l7m3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.nepaltop',
  );
}
